### ISSUE TITLE
Grade gets reset if an asset isn't available

### ISSUE THREAD

**Issue by MitchellBerry** [pegnet/pegnet#104]
If the average is zero then the grade is completely reset back to zero? Doesn't seem like it should happen.

https://github.com/pegnet/pegnet/blob/e950f5cfbb7560a6d6d8529944cbbf23d8ea9260/opr/grading.go#L54-L55

If the final asset isn't available for whatever reason everyone will get the best grade possible irrespective of other values and the opr will be decided on difficulty alone. If any asset isn't available it will void all the previous scores.

Shouldn't an avg of zero simply be ignored?

**Comment by WhoSoup** [comment]
You're right, it shouldn't happen this way. The entire else branch should be removed. 

* If the average is zero, then it means *every entry* is zero and since everyone is in unison, it won't impact the grade at all.
* If the average is non-zero but the record has a zero, the grade should be added the full distance to the average (this does not currently happen)
* The average being zero and the entry having a non-zero value can't happen since negative values are not allowed

**Comment by PaulSnow** [comment]
What we need to do is compute the value of PNT (when we have assets to compute it with).

**Comment by MitchellBerry** [comment]
Fixed!
Thankyou kindly Who!
