### ISSUE TITLE
Getting a robust statistical average for grading

### ISSUE THREAD

**Issue by MitchellBerry** [pegnet/pegnet#106]
Currently we use arithmetic mean to calculate the basis for grading. Mean is inherently susceptible to skew by outliers. While there many different methods for dealing with outliers, simply using median prevents many issues that could arise, it's a robust measure that requires over 50% of malicious entries before reaching it's breakdown point. Mean by comparison is fragile and has a breakdown point of 1/N.

### Hypothetical example:

50 OPR values in the first cut for bitcoin, 49 all recorded the same value of $10,000 except for one outlier of $80,000: 

` XBT Values = [10000, 10000, 10000, ... , 80000]`

**Mean =  $11,400**
**Median = $10,000**

This might not seem problematic at extremes like this with such a simple example, but getting a few invalid values in the first cut can corrupt grading further down the line in favor of the eventual winning opr. 

A miner who knows they have a solid hashrate can submit an outlier into the top 50 and modify all their other entries to be graded above others. Highly recommend replacing the current grading mechanism with median.

### Alternatives:

* Trimming or winsorizing outliers, though when set at an arbitrary percentage its hard to see whether it would be effective. Using standard deviation as a threshold is also quite susceptible to outliers and probably shouldn't be considered when faced with malicious inputs. Winsorizing extreme values to the last previous recorded amount would have the effect of creating inertia for any attempt to dramatically move prices.

* Limit the percentage rate of price movement per block, by either trimming or modifying any value that tries to go beyond that. This is even more fraught with pitfalls and hardly ideal for a basket of vastly different pegs. Currencies rarely move a single percentage point in a day. Some commodities swing wildly, cryptocurrencies can halve in price within hours. Having to make a judgement call on each individual one is impractical at best The only good aspect of restricting movement to a certain percent is that it would avoid flashcrashes and balance out highly turbulent situations.

### Further info

https://en.wikipedia.org/wiki/Central_tendency

https://en.wikipedia.org/wiki/Breakdown_point#Examples

**Comment by WhoSoup** [comment]
Hm, I'm not that good at this kind of math, but does it make a difference that the filter pass only filters out one outlier per round? To get the list of 50 initial candidates down to 10, we do 40 passes in each of which the furthest outlier is removed. The next round then re-calculates the mean of those left, not the original mean.

There are scenarios where it would still be impacted but they require a lot of hashing power to get enough malicious entries into the top 50 to flip the eventual "center" to be part of the malicious set. This is further complicated by the fact that each entry has 20+ assets. 

So let's say you want to influence the value to your benefit.
Scenario A:
* There are at most 24 (<50%) malicious entries

Since the furthest outlier is removed with each pass and then the grade is recalculated from scratch, this means that all outliers will be removed by the 24th pass. In order for one of your entries to survive, they'd have to have a grade better than the furthest outlier. That means the set of malicious entries would have to be closer to the mean than some other entries, which would make them valid entries in the first place.

There's still the possibility of dampening the movement of assets. If you insert your entries somewhere between the 10th and 11th asset, you could "bump" out the lowest or highest "correct" entry and dampen the average. Then in the next block you'd have to stop and have a potential more-than-normal swing in one direction.

That kind of influence is limited by how far the 11th-closest OPR is to the 10th-closest. As long as there are 11 good OPRs (by definition there are 26) in a close cluster, this attack is only viable within the range of good OPRs.

Scenario B:
* There are 25+ (>50%) malicious entries

If you have 26 or more, you have complete control to set whatever price you want. If you have exactly 25, then I believe the tiebreaker is decided by difficulty. If the difficulty happens to be the same (incredibly unlikely) it's whoever submitted the OPR first. If you win the tiebreaker, you also have complete control to influence the set.

Anyway, I'd love to see some input from more mathematically inclined people, but I don't see a serious flaw in the current implementation. If you can find a set of 50 numbers where the set of 26 good entries is influenced to include one of the 24 outliers, please post it!

**Comment by MitchellBerry** [comment]
True, forgot that it filters down and re-calculates each time as a opr is culled. Get the feeling that median is a still the better method for finding the average. 

Really the main way to prove this can be done is by demonstration of some intentionally wrong values producing this outcome, I'll have to work on it.

**Comment by WhoSoup** [comment]
> Really the main way to prove this can be done is by demonstration of some intentionally wrong values producing this outcome, I'll have to work on it.

If it helps, I wrote unit tests for this function a while ago that let me automate testing of different grade values. 
https://github.com/pegnet/pegnet/blob/341e0b0b0787f994a441441226f1115abaec39de/opr/grading_test.go#L275

it already has a bunch of very simple outlier scenarios in it for https://github.com/pegnet/pegnet/issues/58

**Comment by PaulSnow** [comment]
I am not married to what is implemented, but I'd call it an Median Average...

We take the averages, and toss out the entry with the widest variance, then repeat until we end up at 10 winners.  So we are not using the median to select the winners (the center, subject to manipulation by submitting "weighted" entries).  We are using the median to select the most losing (the outliers, eliminating the "weighted" entries, so the final selection of the winners  is not subject to "weighted" entries)

The idea is that the only way to "swing" the prices is to have the most prices.  Any attacker with a minority of prices that tries to move the real average gets eliminated first... so they have no impact.

The real protection then from manipulation is to make it so it is real hard to get a majority.  IF (and I really mean IF) we want to attack that problem, the question is really:  

How do we make it hard to have a majority

I do have an idea about that.  Fix the step before we try and average.  In other words, randomize how the final set is selected, so PoW is critical, but some other component comes into play that thwarts a simple "submit 26 entries with the most hash power with the prices you want".  The current algorithm will just hand that to the guy with that much hash power.

I will write a different issue to cover that approach.

**Comment by PaulSnow** [comment]
See #108 on how to make it hard to dominate the top 50 with PoW

**Comment by MitchellBerry** [comment]
>  If it helps, I wrote unit tests for this function

Thanks Who, was actually playing around with these when I came to the conclusion about averaging. I'll see if I can build a nefarious opr set. 

Keen for the bigger discussion of preventing manipulation in the other issue.

**Comment by Cahl-Dee** [comment]
@MitchellBerry if this is still a topic for discussion please bring it into the discussion in #259
