### ISSUE TITLE
Validation of the Oracle Price Chain

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#11]
Add code to walk the chain from the start to the end, and weed out any OPRs that do not:
    1) have values for some assets.  If someone messes up the app key, they _might_ write a record with some assets set to zero, something that isn't going to happen (or is so unlikely to happen that we can do an emergency fix if, say, the Euro goes to zero.
   2) Check the grading done by the miners.  The 10 payments should all be correct by the standard algorithm for grading OPRs.  Don't include OPRs that you don't think graded the past right.
   3)  Any OPR that has the wrong directory block height for the block it is recorded in should be discarded.

Any other tests we might think of.

**Comment by WhoSoup** [comment]
> 1) have values for some assets. If someone messes up the app key, they _might_ write a record with some assets set to zero, something that isn't going to happen (or is so unlikely to happen that we can do an emergency fix if, say, the Euro goes to zero.

This is an interesting case and this came up in another issue: https://github.com/pegnet/pegnet/issues/104

There's still the possibility of: 
A) a record with one 0-value entry winning (this is an edge case but it's theoretically possible)
B) an internet hiccup and all miners submit a 0 value for an asset (or a significant enough amount do that A) occurs)

In either case, the value of all transactions or conversions to that currency would effectively burn them, and all transactions/conversion from that currency would fail. Obviously not good.

An easy fix would be:
* throw out all OPRs that have a zero-value for any asset 
* AND have the default logic for miners be that if any asset is zero, it uses the winning value from the previous OPR.

That way legit miners will never submit an OPR with a 0-asset, and attackers who try to sneak one in will be thrown out.

**Comment by Emyrk** [comment]
If we take the previous winner, than the price the conversions used is predictable. 

The current design is when you make a conversion, you don't know the rate you will secure. As the rate is determined by the next OPR correct?

If we ever repeat a price, the user could in theory try to find a way to game the system to repeat a good price. If we instead decide to wait for the next winner, then a conversion transaction is delayed, but still unpredictable.

**Comment by WhoSoup** [comment]
> If we take the previous winner, than the price the conversions used is predictable.

this is the value a miner would pick if they can't fetch the value from an exchange, so that they don't submit an opr with a zero value. the other option is for the miner to sit out a block or wait for the asset request to work, though both of those have worse downsides, I think

**Comment by Emyrk** [comment]
Ah I see. Yea, hard thing to decide. We enforce all the assets be present, so we need to put something or sit out....

We should really have redundancy in our data sources. The current api polling overwrites the previous if we use more than 1 data source per asset. We should really append to a list, then avg across the data sources based on volume or something.

**Comment by WhoSoup** [comment]
> Ah I see. Yea, hard thing to decide. We enforce all the assets be present, so we need to put something or sit out....

Had some more time to think about this, and there's also the option of pausing the entire network if an OPR with a zero-value for an asset happens to win, the way it happens if there are no winners.

This would mean that miners are free to submit OPRs with zero values in them. If there's only a handful of miners that submit zero records, they'll get filtered out during grading and nothing goes wrong. If one of the APIs goes down, then the majority of miners will submit zero-records and one of them is likely to win, stalling all transactions during that block.

It has the similar drawback as the other method that a real-life currency swing during the time the network is stalled could be exploited, so I think this is about picking the lesser of two evils. I hope someone more economically inclined than me can figure out which is better.

As long as there's no situation where a block without valid OPRs happens and attacker can set the price arbitrarily, I'm okay with it.

**Comment by Emyrk** [comment]
That is and interesting proposition

**Comment by Emyrk** [comment]
We can move the conversation to here: https://github.com/pegnet/pegnet/issues/190
As it has to do with conversion prices.
