### ISSUE TITLE
Denial of OPR Attack

### ISSUE THREAD

**Issue by sambarnes** [pegnet/pegnet#110]
Currently, OPRs are not signed by the identity they claim to represent.

Say there are two identities Alice and Bob. And Bob decides to not use his identity in his OPRs and instead list Alice's. However Bob's submissions can effectively block Alice's submissions if he mines with a higher difficulty.

If Bob is honest and submitting good OPR estimates, there is no issue since he'd be helping Alice.

 However, if he chooses to submit terrible estimates as Alice's identity (and mines a higher difficulty than actual Alice was able to do) he can beat out Alice's honest submissions with good estimates. Thus denying her ability to have a competing OPR.

The attacker wins so long as they can prevent another user from being able to compete for rewards.

The above is preventable if we include a signature in one of the ExtIDs that covers all other ExtIDs and the entire json content

**Comment by MitchellBerry** [comment]
Can't see how Alice is prevented from submitting her entries here?

 An ID can submit as many entries as they want to.

**Comment by WhoSoup** [comment]
> An ID can submit as many entries as they want to.

At the moment, OPRs have two fields: the miner ID and address. The grading process throws out entries with a duplicate ID, meaning if you achieve a higher difficulty, you can overshadow someone else's entry with one that has a different address.

The "problem" with signing at the moment is that we eventually want to switch to DIDs once those are working, which may not happen before the pegnet launch, so we'd have to change OPR datastructure fairly soon after launch.

I don't think signing an OPR is necessary though, we just need to change the duplicate filter by incorporating the address as well, so that FA1 + ID1 is not the same as FA2 + ID1. That way we also don't need to generate a new DID for every OPR. The only way someone will be able to submit OPRs in someone else's name will be with the same address, in which case I hope the owner of the address doesn't mind!

see pull request below

**Comment by MitchellBerry** [comment]
I see, why throw out the duplicate ID though? What risk does that pose? Because it's the only differentiating factor in the base LXR Hash?

 The entry hashes for duplicated OPR's have unique entryID's, OPR hash itself is useless after the block is done.

**Comment by WhoSoup** [comment]
> I see, why throw out the duplicate ID though? What risk does that pose? Because it's the only differentiating factor in the base LXR Hash?

The risk is that someone with a very high hashing power can keep all high-POW entries instead of just the highest one, drowning out everyone else.

**Comment by MitchellBerry** [comment]
Wouldn't a nonce field somewhere just solve this then as a quick measure? Get that OPR structure is important to get right first, but fields can always be ignored and there's still space in the entry.

**Comment by WhoSoup** [comment]
> Wouldn't a nonce field somewhere just solve this then as a quick measure? Get that OPR structure is important to get right first, but fields can always be ignored and there's still space in the entry.

at the moment, the ID field is that nonce. if they changed their miner IDs for every block, this would also solve the problem mentioned

**Comment by MitchellBerry** [comment]
Yeah that was my questioning before as to why they are thrown out, it's the only field that stops people mining the same value, seemed like a client side problem.

Replacing "miner00X" with a nonce instead fixes this straight away.

**Comment by WhoSoup** [comment]
After some discussion on discord, I feel like the best interim solution is to perform the duplicate check for **OPRHash** rather than miner id. Carl asked me to summarize my fix:

The problem we're facing is that A) an attacker submitting an OPR with the same ID, higher POW, but a different payout address, or B) an attacker submitting an OPR with the same ID, higher POW, but bogus asset numbers.

In the case of A, the attacker would receive any potential payout. In the case of B, nobody gets any money. One solution (suggested by @MitchellBerry ) is to have miners pick random ids for every new OPR that can't be duplicated. This also works but can be very annoying for tracking the performance of individual miners.

If we throw out all duplicate OPRs with the same OPRHash and only keep the highest POW, then an attacker can't overshadow a legitimate OPR in any way. If they change the id OR the payout address OR any of the values, the opr hash changes and it will count as a separate item.

The drawback is that an "attacker" could still submit OPRs using the same identity name, which would have no impact on the miner apart from tracking who submitted what. 

Once DIDs are implemented, we can sign OPRs and a valid signature (which covers oprhash) would be more powerful than the oprhash, effectively upgrading it by verifying both oprhash as well as the ownership of the DID.

**Comment by Cahl-Dee** [comment]
Agreed via Discord that we will discard the duplicate filter for now. Will revisit later.
