### ISSUE TITLE
Provide Miner Statistics 

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#117]
**Description**
Miners need a method to determine their success/attempts. This allows for monitoring and feedback to ensure a miner is properly working. The initial idea was to use balances to track the progress, however with the Goal of FAT integration, it would be a lot of code duplication at this phase. 

This ticket should serve as the discussion page for designing the statistics needed to provide a miner.

**Steps**
- Design the spec
- Create the issues associated with implementing the design

**Conditions of Satisfaction**
- A set of issues that detail the statistics/data needed to support a miner
- The issues should be categorize by milestone and tagged appropriately

**Comment by WhoSoup** [comment]
Fortunately we don't need to track balances at all to do this, miners can calculate this entirely from scanning through/grading the OPRs via the list of winners. We just have to check the payout address of the 10 winning oprs to determine how well they did historically.

Things I would like to track and eventually have visible to miners:
* How many OPRs there are total
* A full breakdown of where the miners landed in the range (ie top10, top50, or below). This is the meat of the matter and should let you know if your miner is competitive, whether competition has grown or shrunk, etc. For the top10 we should provide 10 different points but for the rest a percentage is probably enough.
* Overall payout (can be calculated dynamically from all the wins)

How we actually track this is still up in the air. We can do either by payout address or by miner id (later did), not sure which one is better.

**Comment by sambarnes** [comment]
Since payout address will later be resolved from the miner's DID, I think we should track by the miner-ID

Agree with the stats you've listed out so far. Those should be sufficient for now, just to show we have mining and grading working

**Comment by Emyrk** [comment]
I'm having a hard time figuring out how exactly the format of an api response would look for **#2** in the bullet list. I'd suggest a simple counter?. This is what the popular battle royale games like Fortnite do their for performance reporting for a given user under the hood. Feels pretty similar to our mining.

```
{
    ...
    placements {
        "0": 1,
        "1": 2,
        "2": 0,
        "3": 1,
        ....
        "50": 10,
        "50+": 102      
    }
    ...
}
```

I think this would be pretty simple, and I'd avoid using percentages for performance, as they can get drowned out by volume. Eg, if the miner wins 10% of the time for months, and then starts losing, the percentage will be slowly dragged down. If we use hard counters, the user can make the determinations from the raw data. 

I think it would also be beneficial to be able to query for a counter for a given minerid at a given height. So a miner can eval block ranges.

**Comment by sambarnes** [comment]
Yeah I imagine we could structure it similar to how prometheus does histogram buckets. Where each bucket is cumulative (i.e. # of submissions with rank < 5, # of submissions with rank < 50, etc).

```js
{
	"results": {
		"block_range": {
			"start": 0,
			"end": 2000,
		},
		"placements": {
			"1": 5,
			...
			"10": 100,
			"25": 200,
			"50": 300,
			"100": 400,
			"250": 500,
			"500": 600,
			"1000": 700,
			"2500": 800,
			"5000": 900,
			"10000": 1000,
			"+Inf": 1500,
			"count": 1500,
			"sum": 125000,
		},
		"total_rewards": 1337,
	}
}
```

The `"count"` would be total submissions, and the `"sum"` would be the cumulative sum of all ranks so that you can do `sum / count` to get the average rank for that block range.

And I think it might be wise to include the total rewards rather than let the user compute that themselves. Although rewards are fixed for now, maybe in the future it becomes something like bitcoin where reward amount follows some curve. Or maybe that's never going to happen? Idk, just thinking out loud

**Comment by Emyrk** [comment]
I have no objection to being cumulative. 
Would the total rewards be in PNT?

**Comment by sambarnes** [comment]
I imagine it'll be denominated in PNT. Not sure if there are any plans to allow for automatic conversion of rewards to a different asset type, or if that will always be up to the user to do at a later time

**Comment by WhoSoup** [comment]
Since all the data remains intact we can add very elaborate stats in the future, but specifically for **milestone 1**, I'd like to suggest the following two API calls:

`result`:
input: block height (default = latest), which checks the oprs contained in that block (the winners are set in height+1 or in grader memory for the latest)
returns:
* `payout` the amount of PNT you won
* `position` a list of all the OPRs you submitted that block, with `entry hash`, `miner id`, `position` as int with 0 being the \#1 winner

AND

`performance` 
input: choice of how many blocks to go back in range, or the option of something like 1 block, 6 blocks (hour), and 144 blocks (~day)
returns: three separate cumulative stats in the format of:
* `count` total number of OPRs submitted during that range
* `payout` the amount of pnt you won during that range
* `placement` similar to sam's excellent list from above, this would be a breakdown of how many wins by 1-10, top50
* `hash power` count of how many of your OPRs are above average difficulty and below average difficulty


miners should also receive feedback via console of:
* how many OPRs they submitted last block
* how many of those won 
* pnt payout

**Comment by WhoSoup** [comment]
> I imagine it'll be denominated in PNT. Not sure if there are any plans to allow for automatic conversion of rewards to a different asset type, or if that will always be up to the user to do at a later time

that definitely smells of wallet feature!

**Comment by Emyrk** [comment]
I agree with those two calls. 👍

**Comment by sambarnes** [comment]
> result:
> input: block height (default = latest), which checks the oprs contained in that block (the winners are set in height+1 or in grader memory for the latest)

to do this we need to parse/grade the whole mining chain every time a request is made right? or add the database functionality?

since in order to validate the current block, you need winners from previous, and so on

**Comment by WhoSoup** [comment]
> to do this we need to parse/grade the whole mining chain every time a request is made right? or add the database functionality?
> 
> since in order to validate the current block, you need winners from previous, and so on

validation happens when pegnet is running normally. every factom minute 1 it calls `GetEntryBlocks` which queries and verifies all eblocks, saving the oprs to global variable `OPRBlocks`. `GetPreviousOPRs(height)` gets the most-recent block from that list, so all the necessary data is cached.

the only thing we'd need to add in that regard would be getting the live winners for the currently-being-built OPR, which we could set in the Grader's `run()` (where it also sends the alerts)

**Comment by Emyrk** [comment]
We should really get some organization into objects vs globals. It's hard to find all these things.

**Comment by Emyrk** [comment]
For `hash power` I think we should also have a placement thing. We want to know if we are in or out of the top 50, as the top 50 make it into the grading (right?). 

So since `graded` only grades the top 50, and hash power has a list of all OPRs, we can have that list have larger buckets past 50. Since we want to get into the top 50, where graded we want into the the top 10. So having granularity near those milestones is what we need.
```
{
	"results": {
		"block_range": {
			"start": 201000,
			"end": 2012500,
		},
		"graded": {
			"1": 5,
			...
			"10": 100,
			"25": 200,
			"50": 300,
			"+Inf": 1500,
			"count": 1500,
			"sum": 125000,
		},
		"hash_power": {
			"1": 5,
			...
			"10": 100,
			"25": 200,
			"50": 300,
                        "100": 400,
			"250": 500,
			"+Inf": 1500,
			"count": 1500,
			"sum": 125000,
		},
		"total_rewards": 1337,
	}
}
```
