### ISSUE TITLE
Duplicate computation of difficulty during grading

### ISSUE THREAD

**Issue by PaulBernier** [pegnet/pegnet#139]
If I follow correctly the logic I believe this difficulty computation here https://github.com/pegnet/pegnet/blob/develop/opr/grading.go#L73 may not be necessary as it was already computed previously here https://github.com/pegnet/pegnet/blob/develop/opr/grading.go#L229

**Comment by WhoSoup** [comment]
the logic for that is also wrong. self-reporting the difficulty should allow us to not have to calculate the difficulty for more than `50 + bad submissions` entries 

it should be:
1. sort all entries by self reported difficulty
2. loop over all entries
3. verify that the self-reported difficulty is accurate, otherwise skip over that record
4. add record to list
5. once you have 50 records, break

**Comment by PaulBernier** [comment]
Yes, I believe the miners are already self reporting their difficulty but the code reading/processing it was explicitly not done yet. Provided your benchmarks though, I'd say we do need that for M1, that's a tremendous optimization.

**Comment by PaulBernier** [comment]
I think this is not relevant anymore with the new grading implementation. Closing
