### ISSUE TITLE
Add library support for other polling sources

### ISSUE THREAD

**Issue by MitchellBerry** [pegnet/pegnet#22]
There's a few currency api endpoints that don't require keys or signup, likely useful for testnet participation. 

For example:
https://exchangeratesapi.io/

**Comment by gunsmoke** [comment]
@MitchellBerry @PaulSnow 

What do you think of implementing a simple Weight system to randomly select Sources?

Example config
```ini
	[Oracle]
		APILayerKey=xba
		OpenExchangeRatesKey=fdda
        # digital currencies
		CoinCap=0
        # currency rates
		APILayer=2
		OpenExchangeRates=4
		ExchangeRatesAPI=0
        # precious metals
		Kitco=2
```

#### When we Pull the PegAssets
```go
func PullPEGAssets(config *config.Config) (pa PegAssets) {
```
The config above would result in something like this.
```go
digital_courrencies = ['CoinCap']
currency_rates = ['APILayer', 'APILayer', 'OpenExchangeRates', 'OpenExchangeRates', 'OpenExchangeRates', 'OpenExchangeRates']
precious_metals = ['Kitco', 'Kitco']
```

**Note:** because we always need one of each, CoinCap is set to 0, because `CoinCap` is the default one for digital currencies, it is appended by default.

The proposal, every time PullPEGAssets is called, one of the Sources is randomly selected for each source type.

**Comment by gunsmoke** [comment]
the PR: https://github.com/pegnet/pegnet/pull/77 already implements this.

**Comment by Cahl-Dee** [comment]
Confirmed, already done.
