### ISSUE TITLE
Grader redesign

### ISSUE THREAD

**Issue by Cahl-Dee** [pegnet/pegnet#259]
It has become apparent that the grader needs improvements. 

Goals we are trying to achieve are as follows:
- PegNet prices should reflect as close to the "right" price as possible, this includes encouraging a range of data sources for redundancy
  -  While it may sound counter-intuitive to the above, not penalizing for being "near" the price is critical, as data sources and request timing will not be exact
- A single miner/pool with insane hash power should not fully control the price
- People with low hash power should have a chance to win, even if it's like 0.00001%, similar to Bitcoin.
- tests should be included that tests against known grading issues

Additionally, precision should be added for supporting very low-value assets, such as KRW.

**Comment by sambarnes** [comment]
Python setup for grading comparison:
https://github.com/sambarnes/alchemy/blob/master/DEVELOPMENT.md

**Comment by Emyrk** [comment]
Here is using a 1% `band of acceptability` 
[band_of_accebility (1).txt](https://github.com/pegnet/pegnet/files/3522361/band_of_accebility.1.txt)

![Screenshot from 2019-08-20 14-56-18](https://user-images.githubusercontent.com/5446298/63380185-93c34900-c35b-11e9-9b0f-3630aa2feec7.png)

**Comment by AroundTheBox** [comment]
I don't have a suggestion for a better grading algorithm, but the following might help focus the discussion for how well potential solutions meet your goals:.

Calculate the following for a single miner or pool's hashpower as a percent of the total:
(A) Ability to shift the consensus price.
(B) Expected payout as a percent of the total payout.

The challenge is that we need (A) to be virtually zero for as high of a max hashpower as possible, and we need (B) to be a linear as possible relative to hashpower. If (A) isn't near zero then someone can convert at favorable prices and if (B) isn't linear it will encourage centralization.

**Comment by Emyrk** [comment]
@AroundTheBox I have been playing with the numbers and agree that A and B are a compromise of each other. Nothing is perfect.

A community member asked about going random after some point (like the top 50). We have entry hashes that are effectively random, that we could knock some random records out if we need to. Currently, we grade, and sort by grade each round. We could, for example, every other round, knock out a random.

I don't know the best way to use random, but it is another tool we can use to make things less predictable. The probabilities, in the long run, might work out the same though?

**Comment by AroundTheBox** [comment]
Despite what i said above, there's really only one goal - accurate prices every block. Goal (A) is really just saying how hard it is to create an inaccurate prices and goal (B) is just saying how much people are encouraged to pool resources to potentially create inaccurate prices. The payout structure really only matters to the extent it impacts the main goal. Given that we have accurate prices every block, a secondary goal is to have as simple and elegant a system as possible.

Here are my quick suggestions, for whatever they are worth:

**1. Publish a common API set.** A single large miner has more power and grades better the more variance there is in other miners' prices. To minimize this variance among smaller miners everyone should use the same APIs. In the future we can come up with a governance structure to vote on APIs, and can even use averages of multiple sources, but for now a very quick improvement would be to create a "commonconfig.ini" with a lot of the current information and options cleared out, and have it published. It should include only the default API sources and rankings, so all users have to do is enter their API keys, addresses, and the other quick config options. When most people are using the same APIs it will also be in the interest of the largest miners to conform.

**2. Payout based on grades for each asset individually.** Having no variance among OPRs is already an advantage for large miners when grading a single asset, but that advantage only grows when the grading score is summed across all addresses. Our main goal is also to find the best price for each address individually and not necessarily the best overall set. If prices for 10 assets from miner X are more accurate and prices for 10 other assets from miner Y are more accurate, we should use and pay based on the combination. Grading individually also reduces the advantage for large miners or mining pools. Grading individually helps both (A) and (B) as I outlined before, but it adds complexity and could be difficult to implement. I think each OPR would have to reference a set of OPRs in the previous block, or records the consensus prices from the previous block, or something similar. Also this would create more payout addresses per block and lose nice round numbers in PNT payouts.

**3. Stop grading sooner and add a final PoW step.** Virtually every resonable approach has the same 2 steps:

Step 1 - Protect submissions from Sybil attacks. Currently this is top 50 PoW.
Step 2a - Converge on a final price by removing outliers. Currently this is done by removing each record sequentially using square of squared differences down to the final record.
Step 2b - Converge on final payout set. Currently this is done using the same method as step 2a, with payouts starting at rank 10. There's no reason it has to be the same methodology as in step 2a though.

Step 1 makes sense and I don't think there are any issues with the current methodology.

Step 2a focuses on goal (A) as I outlined in the earlier post. I don't think other methods, like z score, bands, clustering, or anything else are necessarily better for this step. If we grade on individual assets instead of whole asset sets we can just use regular least squares instead of square of squares and get the same result.

Step 2b focuses on goal (B) as I outlined in the earlier post. This is where the problem is with the current method are and what most alternate suggestions are really trying to improve. I suggest we use the same grading as in method 2a down to 25 records (evaluated for each individual asset) and then pay the top PoW score for the remaining set of 25 for each asset.

Someone submitting honest prices and with less than 50% of the hashpower should be paid proportional to their hashpower, meeting goal (B). Also, up to 50% of the hashpower and measured individually for each asset there is very little advantage to submitting identical records, so it is difficult to influence the price, meeting goal (A).

With 51% of the hashpower someone could both get all the payouts and move prices as much as they want, but that's true for most consensus mechanisms.

**Comment by Emyrk** [comment]
@AroundTheBox Grading assets individually is difficult, as we'd have to stick a lot more on-chain to track 32 sets of winners.

Here was 1 suggestion:
1. Use Pow to get to the top 50
2. Use the normal grading algorithm, but allow a difference of same %, what we are calling the band. This means our error function will look like this: (with y = 0 when x < 0.5 with a band of 5%, obviously high)
![error](https://user-images.githubusercontent.com/5446298/63474972-b67b5d80-c440-11e9-82a2-7fe0088d9c2b.png)
This is **band + grade** until we have 25
3. Pay the 25, 200 PNT each
4. Grade to 1 (the medoid of the dataset), this is the winner
5. The winner is the set price for the block

So the resulting price is the same as the current algo, but there is more winners. I don't think we will ever get to be able to change the price such that it's not influenceable by a 51%. This pays out more people though.

Currently, the top miner has on average 23.73 out the top 50. Or ~47.5% of the blocks on average. He is frequently over 50% with over 30, and sometimes at a number like 18.

Whatever algo we come up with, it's hard to prevent that much dominance from drastically shifting the price.


So this focuses on getting the centermost price, while also allowing more people to get paid with less centered prices. As far as how large the band is, I am unsure. But the band does not change the final price.

**Comment by Emyrk** [comment]
The distribution doing above with a 0.5% band on mainnet data. Which I understand is starting to be mostly 1 data source, but the payouts ending being fairer since we pay the top 25

Code on branch `pay_25`

```
{
  "result": {
    "FA1y6uVYV9YYK9fTDiLr1SxACEmwM5Z12jjS7FYVnwyR43d2KvPk": "3800",
    "FA1y6uVYV9YYK9fTDiLr1SxACEmwM5Z12jjS7FYVnwyR43d2KvPk%": "0.23%",
    "FA27RWJcXcr39Bw91jYWXCqWmekSzrbZ1tZSaHsL4Q7ANktx7cNa": "1800",
    "FA27RWJcXcr39Bw91jYWXCqWmekSzrbZ1tZSaHsL4Q7ANktx7cNa%": "0.11%",
    "FA28MV2VvvsdjjgXoHwsadtMWqM5mt7bZU3hMjLuDLLN1DBhK48g": "28400",
    "FA28MV2VvvsdjjgXoHwsadtMWqM5mt7bZU3hMjLuDLLN1DBhK48g%": "1.71%",
    "FA28wF5WSfXVJB5kzLTwsLiGRS4qgAo5iVg4k3fqVPQmNK7PoLhY": "1000",
    "FA28wF5WSfXVJB5kzLTwsLiGRS4qgAo5iVg4k3fqVPQmNK7PoLhY%": "0.06%",
    "FA29P7f8GrdYgNYeMpK7sEJj47ULAciMZFAgXz4WRsSXp48CqmZ6": "200",
    "FA29P7f8GrdYgNYeMpK7sEJj47ULAciMZFAgXz4WRsSXp48CqmZ6%": "0.01%",
    "FA29yP9g4sinwEtEaRcwJD8B6RuHFwMh7eUZD3TKLXvj8mLMpKpx": "5400",
    "FA29yP9g4sinwEtEaRcwJD8B6RuHFwMh7eUZD3TKLXvj8mLMpKpx%": "0.33%",
    "FA2FafCcveuJMt6gMdMH82UTLVreZTVNB3q3cTkFBGXkfGmGDcMp": "1800",
    "FA2FafCcveuJMt6gMdMH82UTLVreZTVNB3q3cTkFBGXkfGmGDcMp%": "0.11%",
    "FA2HFBXnKzPuepewZbTWvsRFQzxTyKaqiz6fpN6UsNNmvgWxb5Wp": "2000",
    "FA2HFBXnKzPuepewZbTWvsRFQzxTyKaqiz6fpN6UsNNmvgWxb5Wp%": "0.12%",
    "FA2L1d6ggHYT1EP9C2CutoWrWFjYMDijjiCXGgoCpA34uZmCRtYq": "800",
    "FA2L1d6ggHYT1EP9C2CutoWrWFjYMDijjiCXGgoCpA34uZmCRtYq%": "0.05%",
    "FA2P7iEBDsPUgmUSGKNEQPKjVUCq9i8Ea59UGJuvFg7Wk9jBoyH4": "24200",
    "FA2P7iEBDsPUgmUSGKNEQPKjVUCq9i8Ea59UGJuvFg7Wk9jBoyH4%": "1.46%",
    "FA2RQKY68LUgptTY225obkHs52K8wUqSGuVmNWaGha96E8qbRdgg": "400",
    "FA2RQKY68LUgptTY225obkHs52K8wUqSGuVmNWaGha96E8qbRdgg%": "0.02%",
    "FA2U4o2qVy1XfeRFt1HKx8GYqWu6ptwN6a8Nn7VZsKvf6b5ehdJc": "4000",
    "FA2U4o2qVy1XfeRFt1HKx8GYqWu6ptwN6a8Nn7VZsKvf6b5ehdJc%": "0.24%",
    "FA2grV2iMPRrLBKx43GBdWvSTUAGbtHqe7R7nzpr397HnLZP9u7p": "70200",
    "FA2grV2iMPRrLBKx43GBdWvSTUAGbtHqe7R7nzpr397HnLZP9u7p%": "4.23%",
    "FA2mPQpBhr7f9XtXMVhsYQjNzsMGv1sqk2dTZp1NyTBuCaR6BjLM": "114600",
    "FA2mPQpBhr7f9XtXMVhsYQjNzsMGv1sqk2dTZp1NyTBuCaR6BjLM%": "6.90%",
    "FA2pGgeAodtmcXqYk32pR3TKXTEuFxERMAXijssf6nuzANMw15kB": "1200",
    "FA2pGgeAodtmcXqYk32pR3TKXTEuFxERMAXijssf6nuzANMw15kB%": "0.07%",
    "FA2t3QDSE36ZKGzcDkFM4XTLCBvv5aq6wCMRK8BJ2xgqqHNRGq8M": "200",
    "FA2t3QDSE36ZKGzcDkFM4XTLCBvv5aq6wCMRK8BJ2xgqqHNRGq8M%": "0.01%",
    "FA2tUTpBuGVUMer4RMjbL4wBLZvbySRjcZXefFZEo66S7k2zA5nQ": "102600",
    "FA2tUTpBuGVUMer4RMjbL4wBLZvbySRjcZXefFZEo66S7k2zA5nQ%": "6.18%",
    "FA2xfw92dBUhBL8TXg7wpke3mSEdvzexqvLqMM9rgt4ZNSYWigLB": "600",
    "FA2xfw92dBUhBL8TXg7wpke3mSEdvzexqvLqMM9rgt4ZNSYWigLB%": "0.04%",
    "FA2y9JXLXJBSrRULfvQeNjYkz2YZsvg4doqUNtRvpTwoZuh6mLdD": "200",
    "FA2y9JXLXJBSrRULfvQeNjYkz2YZsvg4doqUNtRvpTwoZuh6mLdD%": "0.01%",
    "FA2yETQx7RwJ5rRFS7SqB9mcGFUL1Y1qDsa6hSdF3ccKPYTJaskX": "800",
    "FA2yETQx7RwJ5rRFS7SqB9mcGFUL1Y1qDsa6hSdF3ccKPYTJaskX%": "0.05%",
    "FA2yx98grLWwDc3XC9y5BczbAaJ46LTfAhbWW8cC9HGBLMZrVFPp": "200",
    "FA2yx98grLWwDc3XC9y5BczbAaJ46LTfAhbWW8cC9HGBLMZrVFPp%": "0.01%",
    "FA2zTuZ6kbxsXRAwavpYg68jc5uiq39H5xQp8jGSSFD76RnPQj6x": "4000",
    "FA2zTuZ6kbxsXRAwavpYg68jc5uiq39H5xQp8jGSSFD76RnPQj6x%": "0.24%",
    "FA34U4Xvza1doerjpBCF6C4JXRR7xC1NTuRVqUqT7ih7jWc3ARM7": "800",
    "FA34U4Xvza1doerjpBCF6C4JXRR7xC1NTuRVqUqT7ih7jWc3ARM7%": "0.05%",
    "FA36bdk4n23sQzZYLmt2p2CVZ7UxhxUhTqE5T8sU7A6PsAS6Bovt": "2800",
    "FA36bdk4n23sQzZYLmt2p2CVZ7UxhxUhTqE5T8sU7A6PsAS6Bovt%": "0.17%",
    "FA3AtGjMdjjNHugEkmZmYZ6VsDaGzdGmrj2WoQLE9rEJ7RKxYTdY": "800",
    "FA3AtGjMdjjNHugEkmZmYZ6VsDaGzdGmrj2WoQLE9rEJ7RKxYTdY%": "0.05%",
    "FA3CeHGKnCY8aTtHMboJxmcgyzCNDsCaWSYG1B7FQknLoJz2tUTJ": "200",
    "FA3CeHGKnCY8aTtHMboJxmcgyzCNDsCaWSYG1B7FQknLoJz2tUTJ%": "0.01%",
    "FA3DPAoqjyHgjen8fK3iE7g4FnJRvS8WGAicY2iQBTXxWg3cSwaZ": "2000",
    "FA3DPAoqjyHgjen8fK3iE7g4FnJRvS8WGAicY2iQBTXxWg3cSwaZ%": "0.12%",
    "FA3NbQSVTHomV11bVo9iLroJcbZ19c4uEhVC6qhTad5i6R6wKfda": "600",
    "FA3NbQSVTHomV11bVo9iLroJcbZ19c4uEhVC6qhTad5i6R6wKfda%": "0.04%",
    "FA3QNCqwLKSiuAsj5AoKW95xCye2Rz6XiaHgkAqznpYHV7SXxw2x": "199200",
    "FA3QNCqwLKSiuAsj5AoKW95xCye2Rz6XiaHgkAqznpYHV7SXxw2x%": "12.00%",
    "FA3RnrBk34YMquRwjGcj2gAHf7eBDP1BnJYf6MgHiNXbntjwzbvx": "2200",
    "FA3RnrBk34YMquRwjGcj2gAHf7eBDP1BnJYf6MgHiNXbntjwzbvx%": "0.13%",
    "FA3TAeSuLBe6SZpEqGjawXwQ83LrHfndnYccbJn4b2Awk8kXXZZa": "200",
    "FA3TAeSuLBe6SZpEqGjawXwQ83LrHfndnYccbJn4b2Awk8kXXZZa%": "0.01%",
    "FA3WGKnZev7hg2KfHyiUKKCDh4oQvAqR5MMT1DnJbeQ9ftUg2Pwa": "600",
    "FA3WGKnZev7hg2KfHyiUKKCDh4oQvAqR5MMT1DnJbeQ9ftUg2Pwa%": "0.04%",
    "FA3XTdbB9vmvLM1DWHuvhTn5haJgWwN4RpUThqC4wXr4YXAT2Dco": "800",
    "FA3XTdbB9vmvLM1DWHuvhTn5haJgWwN4RpUThqC4wXr4YXAT2Dco%": "0.05%",
    "FA3XVByui2nTmExr8io4w5TZfhtQobaqdoh9CM3LJ2My5btsFhah": "400",
    "FA3XVByui2nTmExr8io4w5TZfhtQobaqdoh9CM3LJ2My5btsFhah%": "0.02%",
    "FA3YweUEJUKezmwQ8m75wATuktLfudbt7LNobA9rexzkcqzNpvXC": "180200",
    "FA3YweUEJUKezmwQ8m75wATuktLfudbt7LNobA9rexzkcqzNpvXC%": "10.86%",
    "FA3aU8zXyDVv72no45Rf1itwqLb5Z3WWVbWVGhCEWjyGshtNBzRM": "841600",
    "FA3aU8zXyDVv72no45Rf1itwqLb5Z3WWVbWVGhCEWjyGshtNBzRM%": "50.70%",
    "FA3d6DuLwGAz6yNpe2zGu7MyGYzebYKsDfX99J5avq98123HdyyQ": "7800",
    "FA3d6DuLwGAz6yNpe2zGu7MyGYzebYKsDfX99J5avq98123HdyyQ%": "0.47%",
    "FA3fuPfEVtNWR9nq5XEcSxvTVL1r9YERrZxpaQmyj5D5HVwtZ1a9": "600",
    "FA3fuPfEVtNWR9nq5XEcSxvTVL1r9YERrZxpaQmyj5D5HVwtZ1a9%": "0.04%",
    "FA3oC7bXxDEaBGmFkm8riUM64vpYVMMaH73VCvXFzNm1KExNYtbX": "46000",
    "FA3oC7bXxDEaBGmFkm8riUM64vpYVMMaH73VCvXFzNm1KExNYtbX%": "2.77%",
    "FA3rj2d3Y88R8pWdZQoRLyACNVJeNZnAwiaYVVYBiPGqoUgc6Jwj": "4800",
    "FA3rj2d3Y88R8pWdZQoRLyACNVJeNZnAwiaYVVYBiPGqoUgc6Jwj%": "0.29%",
    "all": "1660000"
  },
  "error": null
}
```

**Comment by WhoSoup** [comment]
> @AroundTheBox Grading assets individually is difficult, as we'd have to stick a lot more on-chain to track 32 sets of winners.

This has come up before and we actually could do it by reducing the amount of on-chain data. Instead of listing the shorthashes of the 10 winners, we can just use a SHA256 hash over X, where X is a list of 10 winners for each of the 32 assets. This would reduce the human readability of the OPR but should impose little to no additional requirements to graders.

**Comment by WhoSoup** [comment]
I really like the idea of banding the grading like this. It solves a lot of the headaches of not winning because you're off by fractions of a cent. I think we should compare the differences between various APIs to determine an acceptable band %.

**Comment by WhoSoup** [comment]
> @WhoSoup Actually the short hashes provides something interesting. When we decide to change the grading algo again, we can actually drop the first implementation. We can hardcode a checkpoint for the network of the winner of block X. And traverse backwards with the previous winners in the OPR to calculate all the payouts. Ignoring grading entirely

i'm aware but we have so far worked with a 1 KB size constraint. we can't keep that if we increase the size of winners or number of assets by too much.

**Comment by WhoSoup** [comment]
I grabbed all available API data for a duration of about 100 blocks to see what the differences between the various APIs is like: https://docs.google.com/spreadsheets/d/1uy5cbFaRUNA0QN8pPQvzo61slWUwAY2NXGeVKmN6lXA/edit?usp=sharing
1. The first sheet calculates the band for the upcoming grading change. It's listed as full percentage and a line going ABOVE Y=1 means that if everyone else is using source A, someone using source B would not be inside the band. a line that stays <1 means it doesn't matter which api you use, they're all close enough to fall inside the band
2. The other sheets have the actual USD-to-X values in them. You can for example look at the horrible green line on sheet1 (XLM) then look at the sheet for XLM and see that likely coinmarketcap is not a good source for that specific coin

![image](https://user-images.githubusercontent.com/34172041/63850330-14a1c680-c994-11e9-8efe-5cd3bd387bcd.png)
