### ISSUE TITLE
Modularize Grading

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/pegnet#286]
The goal is to create a standalone Grader that can be imported by various projects who want to grade PegNet OPR entries. The goal is to not have redundant implementations for PegNet and fatd, as well as offer a library for any third parties who want to build tools or independently audit the OPR chain. 

The grader module should be format independent. PegNet currently uses the factomproject/factom client whereas FAT uses its own custom client. They return entries in different formats and other projects may have persisted them in databases or import via csv. 

I think the Grading module should work the following way, but if you have different ideas please provide them:
1. Start a new "Block" with metadata such as height and version id
2. Add the list of previous winners
3. Feed in the OPRs either one by one or in bulk
4. Grade the block, returning an ordered list of winners

What format 3 and 4 use is up for debate. My first thought is to just have a function: `block.AddOPR(entryhash []byte, extids [][]byte, data []byte)` to feed in the raw data in an independent manner. The result from 4 could then be just a slice of entryhashes, or a special format that also contains the decoded entries.

That would mean the responsibility of retrieving the data, providing the height, version id, and list of previous winners would fall on the *caller*, keeping this as a minimum module. Ideally the only factom ecosystem dependency this has is the **LXRHash** repo. 

If anyone has differing ideas on what a grading module should do, now is the time to plan it out.

**Comment by WhoSoup** [comment]
After further consideration, there is another complication of the list of Assets and OPR structure definitions, which are currently held in `common.AllAssets` and `opr.OraclePriceRecord`, the latter of which is used both for grading for mining, the latter of which adds a significant amount of extraneous data.

Both of these could be placed in the grader module, with mining using a separate opr struct. Otherwise, we could also spin OPR into its own module, consisting of assets, the opr, and the v1 json and v2 protobuf marshalling.

**Comment by Emyrk** [comment]
## OPR Struct

I think having a proper `opr` struct is hard to avoid, especially with all the new versioning. The opr module has a `SafeMarshal` and `SafeUnmarshal` that can take the version 1 or version 2 data. You can see that here: https://github.com/pegnet/pegnet/blob/PNT-280_protobuf_rebase/cmd/cmd.go#L607 (notice I set the opr version first, to indicate the encoding format). As we release more versions, this keeps your method signatures the same. The current struct can probably use more work to make it a stand-alone thing. 

Also with the RateCalculation work, it was being done on that special AssetList object in the struct: https://github.com/pegnet/pegnet/pull/276/files#diff-bf1b3e5d7a9e785e8c4847ebbd6ccb88R53. Having functions that do rate calculation would mean users do no have to reimplement any of the math, as the order of operations there is critical.

I understand the want of not having a single struct that everyone has to use, but I find it hard to avoid. So I would suggest we create the bare minimum OPR struct, and just properly document it so a caller can reformat it for storage if they need. Ideally, we contain all the required information so the OPR struct can return to the `entryhash []byte, extids [][]byte, data []byte`. Having a function on the OPR to return it to that would make the struct able to be temporary, and only live for as long as it is needed, and not stored in that way.

## Grading module

I like the idea of a module grading block by block. I think that is the cleanest way of doing it, currently, the factom fetching code is very intertwined. I think keeping it simple is fine, and that would keep our documentation of it clean and concise. 

My main comment is that if we create an `OPR` struct, there is value in being able to parse a single OPR without grading. So that option should exist, meaning the `AddOPR` does the parse and the validate, but I think we should also have functions exported to allow for JUST a parse, and JUST a validate. I use this primarily for debugging. I'll see if I can come up with some method definitions?

**Comment by sambarnes** [comment]
> My first thought is to just have a function: block.AddOPR(entryhash []byte, extids [][]byte, data []byte) to feed in the raw data in an independent manner.

I was thinking the same. Working only with bytes will allow us to remain independent from the two Factom Go libs so we don't need to fully commit/refactor to one or the other in the meantime

> The result from 4 could then be just a slice of entryhashes, or a special format that also contains the decoded entries.

The result from 4 should be a special format IMO, so that we can store the computed grade along with the entry in the database. That way we would not have to regrade the whole block if we wanted to recall grade value of individual records.

Also, I think it should be returning more than just the winners --- thinking the full list of records that competed in the grading round.

**Comment by Emyrk** [comment]
> Also, I think it should be returning more than just the winners --- thinking the full list of records that competed in the grading round.

I agree. Currently, we return the top50 in graded order, I think we should stick to that. The sorted list means the winners are in the fist X indices. We should only return the top 50, as we only grade the top 50 honest records, so that is all we can promise.

**Comment by Emyrk** [comment]
> Ideally, we contain all the required information so the OPR struct can return to the entryhash []byte, extids [][]byte, data []byte

Also for this bit. Because v1 is json, this means we might need to store the raw entry content in the OPR to ensure the OPRHash calculation is always deterministic. It feels annoying to have to duplicate our data, but there is no other way I can think of to be able to return an OPR to it's original components.

**Comment by Emyrk** [comment]
@WhoSoup @sambarnes 
Is this what you had in mind? I made the interface that the grading module will adhere too. I tried to include what I think would be useful for the caller in the form of accessors and errors.
https://github.com/pegnet/pegnet/blob/grading_module/grading/interfaces.go

**Comment by Emyrk** [comment]
@WhoSoup one annoying thing about the LXRHash is that we initialize it here:
https://github.com/pegnet/pegnet/blob/master/opr/opr.go#L105

We should make a directory for our seed in https://github.com/pegnet/LXRHash
So you'd import `github.com/pegnet/LXRHash/lxr30`, and all packages using the 30bit will use the same lxr global. If someone wants to change the hashsize and passes, they would have to customize that. But in the general case, this would be sufficient imo.

**Comment by Emyrk** [comment]
> @WhoSoup one annoying thing about the LXRHash is that we initialize it here:
> https://github.com/pegnet/pegnet/blob/master/opr/opr.go#L105
> 
> We should make a directory for our seed in https://github.com/pegnet/LXRHash
> So you'd import `github.com/pegnet/LXRHash/lxr30`, and all packages using the 30bit will use the same lxr global. If someone wants to change the hashsize and passes, they would have to customize that. But in the general case, this would be sufficient imo.

Just remembered why we didn't do this. Then unit testing is a pain. Grr. Trying to think of the best place to store the global.

**Comment by WhoSoup** [comment]
Short update: steven and i had different ideas on how to implement the modularization. it's hard to put it all into words so i wrote a simple implementation of what i had intended: 
https://github.com/WhoSoup/pegnet/tree/PNT-286_moduralize_grading_alt/modules (this code hasn't been tested it exists only to illustrate the concept at the moment so please forgive any glaring errors)

whereas steven's version can be seen at https://github.com/pegnet/pegnet/tree/PNT-286_modularize_grading/modules

steven's is mostly a straightforward moving of the existing code into its own module, separating versions with if statements. the grading module still uses the opr module's format, so the modules are fairly intertwined still

the idea behind mine was to separate v1 and v2 inside the code and just tuck them into an interface. once a specific version is implemented, the code is then set in stone and never has to be touched again instead of having to go back and keep adding if statements in all of the functions. similarly, the opr itself is hidden under an interface.

my approach is more work with code duplication, but the benefit is that it's very modular and adding new versions and testing will be significantly easier

anyway, steven is mulling it over but i wanted to give everyone else a chance to provide some input on this issue

**Comment by WhoSoup** [comment]
> Just remembered why we didn't do this. Then unit testing is a pain. Grr. Trying to think of the best place to store the singleton global.

i propose https://github.com/pegnet/LXRHash/pull/51

**Comment by Emyrk** [comment]
Going the separate v1/v2 code route is better for when we hit a v3. I think to deal with the interface, we are pushing some of the `if version == X` stuff to the caller. Such as `v1` having `PNT` and `v2` having `PEG`. This is now pushed to the caller, where I was trying to maintain a structurally similar OPR to reduce work on the caller.

**Comment by Emyrk** [comment]
After chatting with Who, we had some difference of opinions on the method definitions of the calls that require a graded set, such as `WinnerShortHashes() ...`. In my original interface, these kinds of methods would return an error if the set was upgraded. This does add some additional return checking and makes the code more awkward with the class `if err != nil ...` everywhere. 

In Who's, if the set was upgraded, it would grade the set, and then return the winner short hashes. 

I dislike the idea of having large side effects to what is effectively an accessor, but I do agree that most of the time, the use of the interface would yield the error checking unnecessary (every dev will `Grade()` first surely right, because we'll document it right...). We thought of a compromise though.

`Grade()` can return `GradedBlock` that has all the accessors on it. This means the `BlockGrader` will not ever have a graded set of oprs, but rather it will produce `GradedSets`. These sets are guarenteed to be graded, so the accessors are always safe.This also makes the `GradedSets` immutable, which is something I was aiming for in the first draft of the interface.

**Comment by WhoSoup** [comment]
Alright, got the brunt of the structural work done. Thank you so much @Emyrk for helping with this monumental task. 

The current state of the code can be seen at https://github.com/pegnet/pegnet/tree/PNT-286_moduralize_grading_alt/modules, with the same disclaimer as before: it's mostly structural and not guaranteed to be bug free yet.

I'll type out a more complete documentation/usage when creating the readme, but the gist of it is:

The OPR module contains `V1Content` and `V2Content`, which are json and protobuf respectively, as well as the list of assets contained in each. 

The Grading module has a `BlockGrader` interface that can hold either a V1 or a V2 grader. You initialize a Grader for a certain height and list of previous winners, then proceed to feed it factom entries (in a data independent manner).

When it's time to Grade, the Grader will create an immutable GradedBlock that is built with the fed GradingOPRs. The GradedBlock lets you retrieve the winners and all GradingOPRs that have a grade. Each GradingOPR inside a GradedBlock is aware of its own position and payout, so you can easily access that. 

Note: GradingOPR is more or less the equivalent of a factom.Entry, except all the values are decoded and named

If you see any functionality that's missing or any feature you want, please speak up

**Comment by PaulBernier** [comment]
Really neat! Have you tried using those module to replace current pegnet implementation of grading, for the sake of testing those new interfaces "in real condition"? I think that could be a good test to prove that those interfaces are robust and well designed?

**Comment by Emyrk** [comment]
@PaulBernier I was thinking of building something to dog food it before I integrate it into the existing.

**Comment by Emyrk** [comment]
@WhoSoup a minor thing

I think we should start this iota <https://github.com/pegnet/pegnet/blob/PNT-286_moduralize_grading_alt/modules/opr/opr.go#L8> with a 
```
_ = iota
```

That way an unset value is known to be an invalid opr, rather than a v1.
