### ISSUE TITLE
Pegnet TxID

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#334]
Currently, we use `entryhash` as our `txid`. This is problematic when you realize an entryhash can contain a set of transactions. Pegnet supports tx batching, and we use the `tx-index` to indicate each tx in the batch. I think we should expose this to users and provide a `txid` format that also includes the `tx-index`. If we formalize this now, then all our tooling going forward will adopt this.

For example:
I pay users A and B, I'd get back 2 txids, both for the same entry. They would be:
```
# [tx-index]-[entryhash]
00-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
01-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
```

Then each user can go to the explorer an\
past their txid, `001-afe...` and get their subset of the batch. Rather than seeing the entire set.

**Comment by WhoSoup** [comment]
This is a useful feature. I posted my initial thoughts in the discord but had some time to think about it more. I'm okay with it being a dash ("-"), since those are likely to work everywhere (particularly urls) and make it obvious to anyone that it shouldn't be parsed as hex.

I also think we should use decimal numbers and start counting at 1 rather than 0, without leading zeros. In a 10KB entry there can be potentially hundreds of transactions but I wouldn't want two leading zeros for most entries.

Example:
```
# [tx-index]-[entryhash]
00-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
01-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
01-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
01-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
01-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
01-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
01-afe53d8f7b2e088cb15262ee5fc417e8e436f7592bf967cc283b8edd0a72801f
```

**Comment by Emyrk** [comment]
I like the idea of a `0-` prefix being `all`, since then the format is consistent, and we don't have 2 formats.

The leading 0s I figured would be good for keeping the length consistent. Hashes are always 64 hex characters, and we sometimes do length checks for validation. I like the idea of a consistent length.

**Comment by WhoSoup** [comment]
> Hashes are always 64 hex characters, and we sometimes do length checks for validation. I like the idea of a consistent length.

I disagree, since this is a feature aimed at people (people will likely attempt writing these by hand and requiring leading zeros doesn't make sense there), and I'd also like to futureproof it. If we ever upgrade the transactions to a non-json format, we can easily fit hundreds of transactions into a single entry (upwards of 200). Requiring two leading zeros to futureproof it is not great.

Testing for it shouldn't be a big deal, since we can just assume any string with length > 64 is this format.

**Comment by Emyrk** [comment]
I just realized our api returns 0 based tx indexes.

```
         {
            "hash":"9d5cf82eb16310016962c9abc08a619b02258024b00ce7407eb2761b68e97150",
            "height":213470,
            "timestamp":"2019-10-09T00:46:00+02:00",
            "executed":213470,
            "txindex":0,
            "txaction":1,
            "fromaddress":"FA3pPBWaVjZXhiFiUBdpvyjK84cvjWcZvZqoxeAEsH3rFCtEvEVt",
            "fromasset":"pXAU",
            "fromamount":100000,
            "outputs":[
               {
                  "address":"FA2QdSsWp4MoZVm8RpcnsJXJVAVDvbno5fAD1Qn67knFRJdxsxJU",
                  "amount":100000
               }
            ]
         },
```

That is going to be confusing if we 1 index the prefix, and 0 index the response.

**Comment by WhoSoup** [comment]
> That is going to be confusing if we 1 index the prefix, and 0 index the response.

i agree there's some room for perfection. since this hasn't been released yet, we can have the api just add +1 to txindex, then it would only annoy pegnet developers but not third party developers

the other option is to leave txindex zero based and have the 1-based index just be part of the transaction id. 

that reminds me, is this change supposed to be only second layer, or should we change the api to recognize and return `#-hash` ids?

**Comment by Emyrk** [comment]
I think it would be a good idea to adopt it in the reference code if we want 2nd layers to use it.

Would it be bad to have `entryhashes` and `txids` be different things? We can 0 index the txid, and if you want the batch, you'd provide the entryhash

**Comment by WhoSoup** [comment]
Update: @Emyrk and I have finalized this as:

txid = `index-batchhash`, where `index` is zero-based with no leading zeros required, and "batchhash" refers to either the entryhash of a transactions, an opr entryhash, or a factom txid. Just using "batchhash" without an index refers to a list of all of the transactions inside the batch.

This has been implemented in the newly released transaction history API of pegnetd, see https://github.com/pegnet/pegnetd/wiki/API#get-transaction

**Comment by Emyrk** [comment]
I say we close this issue
