### ISSUE TITLE
Create a set of tests to evaluate grading of OPR records

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#80]
Collect sample data, form into a unit test, and make sure grading handles identified cases.

**Comment by MitchellBerry** [comment]
Current non-working tests are due to the map in `RemoveDuplicateMiningIDs`.  The chance of a duplicate is infinitesimally small but for now randomly handled in grading. There seemed to be the opinion on discord that duplicated difficulties should be graded in entry order, which seems reasonable. Not sure it's worth the effort but getting deterministic results out of the duplicate ID process is doable.  

For now to get the more tests rolling along perhaps adding tiny extra amount to the difficulty based on array order? This way we can have an implicit guarantee that opr's set at the same difficulty level will always be sorted in original (1...10) order

**Comment by Cahl-Dee** [comment]
Handle this during the Grading Refactor #259
